### ISSUE TITLE
ORC 1.7.4-SNAPSHOT fails with Iceberg Nan count tests

### ISSUE THREAD

**Issue by williamhyun** [apache/orc#1075]
- https://github.com/williamhyun/iceberg/runs/5802512738?check_suite_focus=true

```
org.apache.iceberg.data.TestMetricsRowGroupFilter > testIsNaN[format = orc] FAILED
    java.lang.AssertionError: Should read: NaN counts are not tracked in Parquet metrics
        at org.junit.Assert.fail(Assert.java:89)
        at org.junit.Assert.assertTrue(Assert.java:42)
        at org.apache.iceberg.data.TestMetricsRowGroupFilter.testIsNaN(TestMetricsRowGroupFilter.java:308)

org.apache.iceberg.data.TestMetricsRowGroupFilter > testNotNaN[format = orc] FAILED
    java.lang.AssertionError: Should read: NaN counts are not tracked in Parquet metrics
        at org.junit.Assert.fail(Assert.java:89)
        at org.junit.Assert.assertTrue(Assert.java:42)
        at org.apache.iceberg.data.TestMetricsRowGroupFilter.testNotNaN(TestMetricsRowGroupFilter.java:320)
```

https://github.com/apache/orc/pull/1055 looks relevant to this issue.

**Comment by dongjoon-hyun** [comment]
Thank you for reporting, @williamhyun .

**Comment by guiyanakuang** [comment]
Thanks to capturing these failed tests, @williamhyun
I conducted some investigation.
Prior to #1055, it was just coincidence that these tests would pass, after #1055 was fixed so that the push-down judgement could continue to be executed.
1. `testIsNaN[format = orc]` This test is no longer working.
When orc is not written to Double.NaN, and DoubleStatistics sum is a finite value, we can correctly push down `no_nans = NaN` and skip this stripe.
2. `testNotNaN[format = orc]` is still a valid test.
The reason this test doesn't pass is that the statistics check for the Float type is missing.
https://github.com/apache/orc/blob/70c504cbd759342476d2fb2c9cc75a5025cb7c11/java/core/src/java/org/apache/orc/impl/RecordReaderImpl.java#L696-L703
`category == TypeDescription.Category.DOUBLE || category == TypeDescription.Category.FLOAT`

**Comment by williamhyun** [comment]
Thank you @guiyanakuang !
I am retesting on both Iceberg and Spark.

**Comment by dongjoon-hyun** [comment]
I also quickly re-checked the Iceberg test. So, `TestMetricsRowGroupFilter` passed except the following one mentioned by @guiyanakuang .

```
shouldRead = shouldRead(isNaN("no_nans"));
Assert.assertTrue("Should read: NaN counts are not tracked in Parquet metrics", shouldRead);
```

**Comment by dongjoon-hyun** [comment]
If you get the results, please share them to the dev mailing list, @williamhyun .

**Comment by dongjoon-hyun** [comment]
@williamhyun 
ORC-1147 landed to main/branch-1.7/1.6. Could you rerun the integration tests, please?

**Comment by williamhyun** [comment]
Thank you, I am rerunning the tests here:
- https://github.com/williamhyun/iceberg/pull/1
- https://github.com/williamhyun/spark/pull/3

**Comment by dongjoon-hyun** [comment]
Thank you for rerunning it. Yes, I saw Spark passed and Iceberg has only the following. If we comment out the test, it will pass cleanly.
```
org.apache.iceberg.data.TestMetricsRowGroupFilter > testIsNaN[format = orc] FAILED
    java.lang.AssertionError: Should read: NaN counts are not tracked in Parquet metrics
        at org.junit.Assert.fail(Assert.java:89)
        at org.junit.Assert.assertTrue(Assert.java:42)
        at org.apache.iceberg.data.TestMetricsRowGroupFilter.testIsNaN(TestMetricsRowGroupFilter.java:308)
```

**Comment by dongjoon-hyun** [comment]
BTW,
- if you feel ok, please close this issue and move forward, @williamhyun . :)
- Since the same patches are in the branch-1.6, I'll trigger integration test for them separately as a release manager of Apache ORC 1.6.14 as a part of https://github.com/apache/orc/issues/1081 .

**Comment by dongjoon-hyun** [comment]
One more thing. @williamhyun . If you don't mind, please follow the style of https://github.com/apache/orc/issues/1081 and update your release issue, https://github.com/apache/orc/issues/1046 . It will be greatly helpful for people to track your efforts and progress.

**Comment by dongjoon-hyun** [comment]
Thank you for verifying and closing this.
