### ISSUE TITLE
@coderex2522  Has the ORC file encryption and decryption functionality been implemented?

### ISSUE THREAD

**Issue by zxf216** [apache/orc#1615]
> Hi @dongjoon-hyun Do we have jira to track the work?

@deshanxiao Not yet. @coderex2522 is working on it already. Will create JIRAs later.

_Originally posted by @wgtmac in https://github.com/apache/orc/issues/1183#issuecomment-1259238037_

**Comment by dongjoon-hyun** [comment]
Sorry but let me close this as duplication of #1183 and #1610 . Since it's already answered, you don't need to keep re-creating the same issues again and again, @zxf216 .
- If you want to open something, #1183 is what you want.
- If you want to open JIRA issues, https://issues.apache.org/jira/projects/ORC/issues/ is what you want.
